version: '3.1'

services: 
  
  nginx:
    image: nginx:latest
    container_name: mywordpress_nginx # name of container image
    ports:
        - 80:80
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - .:/var/www/html/
    environment:
      - NGINX_HOST=mywordpress.test
      - NGINX_PORT=80
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mywordpress.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    links:
        - wordpress
    restart: "no"
    # docker run --name some-wordpress --link=some-mysql:mysql -e WORDPRESS_DB_NAME=some_wordpress -v /var/docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini -v /var/docker/phpinfo.php:/var/www/html/phpinfo.php -p 8081:80  -d wordpress
  wordpress:
    image: wordpress:5.1.0-php7.3-fpm
    depends_on:
      - mysql
    container_name: mywordpress_wordpress # name of container image
    restart: "no"
    ports:
      - 9000:9000
    working_dir: /var/www/html
    restart: on-failure:5
    volumes:
      - .:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:     
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: mywordpress-wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: S[-cRet@me1131 # you can edit password
      WORDPRESS_TABLE_PREFIX: tittee_ # put your table prefix
      WORDPRESS_DEBUG: 1 
    

  mysql:
    image: mariadb:10.3.6
    container_name: mywordpress_mysql # name of container image
    restart: "no"
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mywordpress-wp
      MYSQL_ROOT_PASSWORD: S[-cRet@me1131 # you can edit password
      MYSQL_USER: root
      MYSQL_PASSWORD: S[-cRet@me1131 # you can edit password
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mywordpress_phpmyadmin # name of container image
    environment:
      - PMA_HOST=mywordpress_mysql
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=S[-cRet@me1131 # you can edit password
    restart: "no"
    ports:
      - 8090:80
    volumes:
      - /sessions
    depends_on:
      - mysql
    
volumes:
  db_data: